
# HTTP Server
server:  
  port: 8056   # HTTP port

# Spring properties
spring:  
  application:
    name: contacts

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/