# HTTP Server
server:  
  port: 8057   # HTTP port

# Spring properties
spring:  
  application:
    name: profesores

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
